// 12권 교재 메타데이터 (integrate_v2.py LEVELS 배열 기반)
export const BOOKS = [
  {
    id: 'hangul',
    title_ko: '한글반 교재',
    title_ja: 'ハングル班 テキスト',
    title_en: 'Hangul Class Textbook',
    series: '안녕, 서울',
    cefr: 'Pre-A1',
    category: 'basic',
    previewPages: 3,
    pdfFile: 'hangul.pdf',
    encryptedFile: 'hangul.enc',
    previewFile: 'hangul-preview.pdf',
    color: '#ff69b4',
    description_ko: '한글 읽기·쓰기 기초',
    description_ja: 'ハングル読み書きの基礎',
    description_en: 'Hangul Reading & Writing Basics'
  },
  {
    id: 'beginner',
    title_ko: '초급 회화반 교재',
    title_ja: '初級会話班 テキスト',
    title_en: 'Beginner Conversation Textbook',
    series: '안녕, 서울',
    cefr: 'A1-A2',
    category: 'beginner',
    previewPages: 3,
    pdfFile: 'beginner.pdf',
    encryptedFile: 'beginner.enc',
    previewFile: 'beginner-preview.pdf',
    color: '#da70d6',
    description_ko: '여행 생존 회화',
    description_ja: '旅行サバイバル会話',
    description_en: 'Travel Survival Conversation'
  },
  {
    id: 'inter1',
    title_ko: '중급1 회화반 교재',
    title_ja: '中級1会話班 テキスト',
    title_en: 'Intermediate 1 Textbook',
    series: '안녕, 서울',
    cefr: 'A2-B1',
    category: 'intermediate',
    previewPages: 3,
    pdfFile: 'inter1.pdf',
    encryptedFile: 'inter1.enc',
    previewFile: 'inter1-preview.pdf',
    color: '#4fc3f7',
    description_ko: '친구 사귀기·감정 표현',
    description_ja: '友達作り・感情表現',
    description_en: 'Making Friends & Expressing Emotions'
  },
  {
    id: 'inter2',
    title_ko: '중급2 회화반 교재',
    title_ja: '中級2会話班 テキスト',
    title_en: 'Intermediate 2 Textbook',
    series: '안녕, 서울',
    cefr: 'B1',
    category: 'intermediate',
    previewPages: 3,
    pdfFile: 'inter2.pdf',
    encryptedFile: 'inter2.enc',
    previewFile: 'inter2-preview.pdf',
    color: '#4db6ac',
    description_ko: '생활 한국어·행정',
    description_ja: '生活韓国語・行政',
    description_en: 'Daily Korean & Administration'
  },
  {
    id: 'inter3',
    title_ko: '중급3 회화반 교재',
    title_ja: '中級3会話班 テキスト',
    title_en: 'Intermediate 3 Textbook',
    series: '안녕, 서울',
    cefr: 'B1-B2',
    category: 'intermediate',
    previewPages: 3,
    pdfFile: 'inter3.pdf',
    encryptedFile: 'inter3.enc',
    previewFile: 'inter3-preview.pdf',
    color: '#00ced1',
    description_ko: '사회·문화 이해',
    description_ja: '社会・文化理解',
    description_en: 'Society & Culture Understanding'
  },
  {
    id: 'adv1',
    title_ko: '고급1 교재',
    title_ja: '上級1 テキスト',
    title_en: 'Advanced 1 Textbook',
    series: '안녕, 서울',
    cefr: 'B2',
    category: 'advanced',
    previewPages: 3,
    pdfFile: 'adv1.pdf',
    encryptedFile: 'adv1.enc',
    previewFile: 'adv1-preview.pdf',
    color: '#ffd54f',
    description_ko: '뉴스·시사 토론',
    description_ja: 'ニュース・時事討論',
    description_en: 'News & Current Affairs Discussion'
  },
  {
    id: 'adv2',
    title_ko: '고급2 교재',
    title_ja: '上級2 テキスト',
    title_en: 'Advanced 2 Textbook',
    series: '안녕, 서울',
    cefr: 'B2-C1',
    category: 'advanced',
    previewPages: 3,
    pdfFile: 'adv2.pdf',
    encryptedFile: 'adv2.enc',
    previewFile: 'adv2-preview.pdf',
    color: '#ff8a65',
    description_ko: '비즈니스 한국어',
    description_ja: 'ビジネス韓国語',
    description_en: 'Business Korean'
  },
  {
    id: 'adv3',
    title_ko: '고급3 교재',
    title_ja: '上級3 テキスト',
    title_en: 'Advanced 3 Textbook',
    series: '안녕, 서울',
    cefr: 'C1',
    category: 'advanced',
    previewPages: 3,
    pdfFile: 'adv3.pdf',
    encryptedFile: 'adv3.enc',
    previewFile: 'adv3-preview.pdf',
    color: '#e57373',
    description_ko: '문학·학술 한국어',
    description_ja: '文学・学術韓国語',
    description_en: 'Literature & Academic Korean'
  },
  {
    id: 'spinA',
    title_ko: '스핀오프A 유코편',
    title_ja: 'スピンオフA ユコ編',
    title_en: 'Spin-off A: Yuko',
    series: '안녕, 서울',
    cefr: 'A2-B1',
    category: 'spinoff',
    previewPages: 3,
    pdfFile: 'spinA.pdf',
    encryptedFile: 'spinA.enc',
    previewFile: 'spinA-preview.pdf',
    color: '#ff69b4',
    description_ko: '유코의 한국 유학 이야기',
    description_ja: 'ユコの韓国留学物語',
    description_en: "Yuko's Study Abroad Story"
  },
  {
    id: 'spinB',
    title_ko: '스핀오프B 아미편',
    title_ja: 'スピンオフB アミ編',
    title_en: 'Spin-off B: Ami',
    series: '안녕, 서울',
    cefr: 'A2-B1',
    category: 'spinoff',
    previewPages: 3,
    pdfFile: 'spinB.pdf',
    encryptedFile: 'spinB.enc',
    previewFile: 'spinB-preview.pdf',
    color: '#da70d6',
    description_ko: '아미의 K-POP 도전기',
    description_ja: 'アミのK-POPチャレンジ',
    description_en: "Ami's K-POP Challenge"
  },
  {
    id: 'spinC',
    title_ko: '스핀오프C 루이편',
    title_ja: 'スピンオフC ルイ編',
    title_en: 'Spin-off C: Rui',
    series: '안녕, 서울',
    cefr: 'A2-B1',
    category: 'spinoff',
    previewPages: 3,
    pdfFile: 'spinC.pdf',
    encryptedFile: 'spinC.enc',
    previewFile: 'spinC-preview.pdf',
    color: '#00ced1',
    description_ko: '루이의 서울 맛집 탐방',
    description_ja: 'ルイのソウルグルメ探訪',
    description_en: "Rui's Seoul Food Tour"
  }
];

export const CATEGORIES = [
  { id: 'all', label_ko: '전체', label_ja: '全て', label_en: 'All' },
  { id: 'basic', label_ko: '한글반', label_ja: 'ハングル', label_en: 'Hangul' },
  { id: 'beginner', label_ko: '초급', label_ja: '初級', label_en: 'Beginner' },
  { id: 'intermediate', label_ko: '중급', label_ja: '中級', label_en: 'Intermediate' },
  { id: 'advanced', label_ko: '고급', label_ja: '上級', label_en: 'Advanced' },
  { id: 'spinoff', label_ko: '스핀오프', label_ja: 'スピンオフ', label_en: 'Spin-off' }
];
